config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {
    sign_up: 'register',
    sign_in: 'login'
  }, controllers: {
    registrations: 'registrations'
  }

  scope '/admin' do
    resources :users do
      collection do
        get :profile_partial
      end

      member do
        put :toggle_approbation
      end
    end
  end

  resources :appointments
  resources :reports do
    collection do
      post :bulk_create
    end

    member do
      get :complete
    end
  end
  resources :patients
  resources :exams
  resources :batteries do
    collection do
      put :update_order
    end
  end

  resources :documents, only: [:destroy]

  root 'appointments#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments, dependent: :destroy
  belongs_to :role

  belongs_to :profile, polymorphic: true
  accepts_nested_attributes_for :profile

  after_create :send_admin_mail

  PROFILE_TYPES = ['CesoProfile', 'BusinessProfile']

  # rails g model GuestBusinessProfile name last_name position phone
  # rails g model GuestPersonProfile name last_name position phone rut passport address birth_date:date
  # rails g model BusinessProfile name last_name username branch:belongs_to payment_agreement
  # rails g model CesoProfile name last_name branch:belongs_to
  #
  #
  # rails g model Business name address rut activity

  def self.parse_profile_type(profile_name)
    profile_type_name = PROFILE_TYPES.detect { |p| profile_name == p }
    profile_type_name.underscore.downcase if profile_type_name.present?
  end

  # Necesario para que el formulario de registro con fields_for cree el
  # perfil según el tipo que se le pasa como hidden field
  def build_profile(params)
    self.profile = profile_type.constantize.new(params)
  end

  # Mass assignment is a feature of Rails which allows an application to create
  # a record from the values of a hash. Example: User.new(params[:user])
  # Unfortunately, if there is a user field called admin which controls
  # administrator access, now any user can make themselves an administrator
  # with a query like.


  # Activación de cuenta por parte de un admin
  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    approved? ? super : :not_approved
  end

  def send_admin_mail
    # Acá va un mail avisándole a un admin que alguien se registró
    AdminMailer.new_user_waiting_for_approval(email).deliver
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end
  # Fin activación de cuenta por parte de un admin
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :toggle_approbation]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.password = Devise.friendly_token.first(8)

    respond_to do |format|
      if @user.save
        @user.send_reset_password_instructions
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # Remove password from params if it's blank of Devise fails validations
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /admin/users/profile_partial?profileType=CesoProfile
  def profile_partial
    @user = User.new
    @user.profile = params[:profile_type].constantize.new
    @profile_type = User.parse_profile_type params[:profile_type]
  end

  # PUT /admin/users/:id/toggle_approbation
  def toggle_approbation
    @user.approved = @user.approved? ? false : true
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'Se actualizó la aprobación' }
      else
        format.html { render :index }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :role_id,
      :profile_type,
      profile_attributes: [:id, :name, :branch_id, :last_name, :payment_agreement]
    )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_profile_fields(user)
    profile_info = []
    user.profile.fields.each do |field, title|
      profile_info << { title: title, data: user.profile.send(field) }
    end
    profile_info
  end

  def profile_titles(user)
    titles = []
    user.profile.fields.each do |_, title|
      titles << title
    end
    titles
  end

  def profile_data(user)
    data = []
    user.profile.fields.each do |field, _|
      data << user.profile.send(field)
    end
    data
  end
end

app/views/users/edit.html.erb
<h1>Editar usuario</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.select :role_id, options_from_collection_for_select(Role.all, :id, :name) %>
  </div>

  <%= render "users/profile_partials/#{User.parse_profile_type(@user.profile_type)}", f: form %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Lista de usuarios', users_path %> |
<%= link_to 'Nuevo usuario', new_user_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<% @users.each do |user| %>
  <h3>
    <%= link_to user.email, user %>
    <%= link_to '[X]', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to "#{user.approved? ? 'Desactivar' : 'Activar'}", toggle_approbation_user_path(user), method: :put %>
  </h3>

  <ul>
    <li>Rol: <%= user.role.name %></li>
    <%= render "users/profile_infos/#{User.parse_profile_type(user.profile_type)}_info", user: user %>
  </ul>
<% end %>

<br>

<%= link_to 'Crear usuario', new_user_path %>

app/views/users/new.html.erb
<h1>Crear usuario</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.select :role_id, options_from_collection_for_select(Role.all, :id, :name, @user.role_id) %>
  </div>

  <div class="field">
    <%= form.label :profile_type %>
    <%= form.select :profile_type, [[], ['CESO', 'CesoProfile'], ['Empresa', 'BusinessProfile']], {}, id: 'profile' %>
  </div>

  <div id="profile_fields">
    <% if @user.profile %>
      <%= render "users/profile_partials/#{User.parse_profile_type @user.profile_type}", f: form %>
    <% end %>
    <div id="loader">
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Lista de usuarios', users_path %>

app/views/users/profile_partial.js.erb
<%
  # Se extrae el form builder de un formulario para el modelo User
  # para poder pasárselo al parcial que se renderea condicionalmente
  form_builder = nil
  form_for @user, url: '' do |f|
    form_builder = f
  end
%>

var profileFieldsSelector = $('#profile_fields');
<% if @profile_type.nil? %>
  profileFieldsSelector.html('');
<% else %>
  profileFieldsSelector.html(
    '<%= j render("users/profile_partials/#{@profile_type}", f: form_builder) %>'
  );
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.email %></h1>
<ul>
  <li>Activo: <%= @user.approved ? 'Sí' : 'No' %></li>
  <li>Rol: <%= @user.role.name %></li>
  <%= render "users/profile_infos/#{User.parse_profile_type(@user.profile_type)}_info", user: @user %>
</ul>

<br>

<%= link_to 'Lista de usuarios', users_path %>