config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {
    sign_up: 'register',
    sign_in: 'login'
  }, controllers: {
    registrations: 'registrations'
  }

  scope '/admin' do
    resources :users do
      collection do
        get :profile_partial
      end

      member do
        put :toggle_approbation
      end
    end
  end

  resources :appointments
  resources :reports do
    collection do
      post :bulk_create
    end

    member do
      get :complete
    end
  end
  resources :patients
  resources :exams
  resources :batteries do
    collection do
      put :update_order
    end
  end

  resources :documents, only: [:destroy]

  root 'appointments#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :battery_offerings
  has_many :batteries, through: :battery_offerings

  has_one :account
end

app/models/exam.rb
class Exam < ApplicationRecord
  include Formable

  has_many :exam_selections, dependent: :destroy
  has_many :batteries, through: :exam_selections
  validates_uniqueness_of :name


  def battery_relations_except(battery_ids)
    ExamSelection
      .where(exam: self)
      .where
      .not(battery_id: battery_ids)
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.require(:exam).permit!
      # params.require(:exam).permit(
      #   :name,
      #   :price,
      #   form_fields_attributes: [
      #     :id, :label, :required, :type, :exam_id, :_destroy
      #   ],
      #   battery_ids: []
      # )
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_exam_association_fields.html.erb
<fieldset>
  <%= f.label :exam_battery_id, class: 'hidden' %>
  <%= f.select :exam_battery_id,
               options_from_collection_for_select(
                   @exam_batteries,
                   'id',
                   'name',
                   f.object.exam_battery_id
               ) %>

  <%= f.label :order, class: 'hidden' %>
  <%= f.number_field :order %>

  <%= f.hidden_field :_destroy %>
  <p class="remove_fields" style="text-decoration: underline; color: red; cursor: pointer;">Eliminar</p>
</fieldset>

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <h2>Campos</h2>
  <%= form.fields_for :form_fields do |f| %>
    <%= render 'form_field_fields', f: f %>
  <% end %>
  <%= link_to_add_fields 'Agregar campo', form, :form_fields %>

  <h2>Agregar a batería(s)</h2>
  <div class="field">
    <%= form.label :battery_ids %>
    <% selected = exam.batteries.collect { |b| b.id } %>
    <% # include_blank evita MOSTRAR la primera opción en blanco %>
    <% # include_hidden evita ENVIAR el primer valor en blanco en el hash de baterías %>
    <%= form.select :battery_ids,
                    options_from_collection_for_select(Battery.all, :id, :name, selected),
                    { include_blank: false, include_hidden: false },
                    multiple: true %>
  </div>

  <div class="actions" style="margin-top: 30px;">
    <%= form.submit %>
  </div>
<% end %>

app/views/exams/_form_field_fields.html.erb
<fieldset>
  <%= f.label :label %>
  <%= f.text_field :label %>

  <%= f.label :required %>
  <%= f.check_box :required %>

  <%= f.label :type %>
  <%= f.select :type, %w[TextField IntegerField SingleChoiceField AttachmentField] %>

  <%= f.label :length %>
  <%= f.select :length, [['Largo', 'long'], ['Mediano', 'medium'], ['Corto', 'short']] %>

  <%= f.fields_for :options do |options_builder| %>
    <%= render 'option_fields', f: options_builder %>
  <% end %>
  <%= link_to_add_fields 'Agregar opción', f, :options %>

  <br /><br />
  <%= f.hidden_field :_destroy %>
  <%= link_to 'Eliminar campo', '#', class: 'remove_fields' %>
</fieldset>

app/views/exams/_option_fields.html.erb
<fieldset>
  <%= f.label :label %>
  <%= f.text_field :label %>

  <%= f.label :value %>
  <%= f.text_field :value %>

  <%= f.hidden_field :_destroy %>

  <%= link_to 'Eliminar opción', '#', class: 'remove_fields2' %>
</fieldset>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.name %></td>
        <td><%= exam.price %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exam.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @exam.price %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/exams/update.js.erb
alert('Actualizado!');