config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {
    sign_up: 'register',
    sign_in: 'login'
  }, controllers: {
    registrations: 'registrations'
  }

  scope '/admin' do
    resources :users do
      collection do
        get :profile_partial
      end

      member do
        put :toggle_approbation
      end
    end
  end

  resources :appointments
  resources :reports do
    collection do
      post :bulk_create
    end

    member do
      get :complete
    end
  end
  resources :patients
  resources :exams
  resources :batteries do
    collection do
      put :update_order
    end
  end

  resources :documents, only: [:destroy]

  root 'appointments#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  include Submittable

  validates_presence_of :patient
  # validate :report_not_completed, on: :update

  belongs_to :patient
  accepts_nested_attributes_for :patient

  belongs_to :appointment

  # Este método devuelve una lista de hashes. Cada hash tiene una batería
  # y los exámenes que contiene. Sólo se muestran exámenes no repetidos.
  # Si una batería no tiene exámenes no repetidos, no se muestra dicha batería.
  # Se pueden mostrar directamente estos exámenes en el PDF. Están ordenados
  # según el orden de la batería en forma ascendente
  def batteries_with_exams
    result = []
    batteries.order(:order).each do |battery|
      temp = { battery: battery, exams: [] }
      if result.empty?
        battery.exams.map do |e|
          temp[:exams] << e
        end
      else
        battery.exams.each do |exam|
          exam_already_added = false
          result.each do |jash|
            exam_already_added = true if jash[:exams].include?(exam)
          end
          temp[:exams] << exam unless exam_already_added
        end
      end
      result << temp if temp[:exams].size > 0
    end
    result
  end

  def batteries
    Battery
      .joins(:exam_selections)
      .where(exam_selections: appointment.exam_selections)
      .distinct
  end

  def exams
    Exam
      .joins(:exam_selections)
      .where(exam_selections: appointment.exam_selections)
      .distinct
    # appointment.exam_selections.map { |es| es.exam }.uniq
  end

  def exam_selections
    ExamSelection.where(battery: appointment.batteries)
  end

  def create_fields
    appointment.batteries.each do |battery|
      ExamSelection.where(battery: battery).each do |selection|
        # cada selection identifica a un examen de la batería
        selection.exam.form_fields.each do |field|
          form_values.create!(
            form_field: field,
            value: nil
          )
        end
      end
    end
  end

  def complete
    self.completed = true
    self.snapshot = generate_snapshot
    save ? true : false
  end

  def generate_snapshot
    full_report = { created_at: Time.now, batteries: [] }
    batteries_with_exams.each do |element|
      battery = element[:battery]
      new_battery = { name: battery.name, exams: [] }
      element[:exams].each do |exam|
        new_exam = { name: exam.name, fields: [] }
        exam.form_fields.each do |field|
          new_field = {
            label: field.label,
            required: field.required,
            type: field.type,
            min: field.min,
            max: field.max,
            value: FormValue.find_by(form_field: field).try(:value)
          }
          new_exam[:fields] << new_field
        end
        new_battery[:exams] << new_exam
      end
      full_report[:batteries] << new_battery
    end
    full_report
  end

  def create_form_values!
    exams.each do |exam|
      exam.form_fields.each do |field|
        form_values.create!(form_field: field, value: nil)
      end
    end
  end

  private

  def report_not_completed
    if self.completed? && self.snapshot.present?
      errors[:base] << 'No se puede editar un informe completado.'
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :destroy, :complete]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @snapshot = @report.snapshot
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        @report.create_form_values!
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def bulk_create
    # TODO: Refactor. Se maneja el rendereo de una vista en otra en caso de error
    return redirect_to appointment_path(report_params[:appointment_id]), alert: "Error" if report_params[:patient_ids].nil? || report_params[:patient_ids].empty?
    report_params[:patient_ids].each do |patient_id|
      report = Report.new(
        patient_id: patient_id,
        appointment_id: report_params[:appointment_id]
      )

      Report.transaction do
        begin
          # TODO: esto debería ser al revés. Crear los form values en memoria y
          # luego guardar todo el objeto report con sus hijos (form_values)
          report.save!
          report.create_form_values!
        rescue StandardError
          return redirect_to appointment_path(report_params[:appointment_id]), alert: "Error creando reporte para #{Patient.find_by_id(patient_id).name}"
        end
      end
    end

    redirect_to reports_path, notice: 'Reports were successfully created.'
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete
    respond_to do |format|
      if @report.complete
        format.html { redirect_to @report, notice: 'Reporte completado.' }
      else
        format.html { redirect_to edit_report_path @report }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      # params.require(:report).permit!
      params.require(:report).permit(
        :completed,
        :patient_id,
        :conclusions,
        :appointment_id,
        form_values_attributes: [
          :id,
          :form_field_id,
          :report_id,
          :value,
          documents_attributes: [
            :id,
            :description,
            document: []
          ]
        ],
        patient_attributes: [:id, :name, :rut, :phone],
        patient_ids: []
      )
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true, multipart: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Datos Paciente</h2>
  <%= form.fields_for :patient do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :rut %>
      <%= f.text_field :rut %>
    </div>

    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>
  <% end %>

  <h2>Baterías</h2>
  <% report.batteries_with_exams.each do |hash| %>
    <% # cada elemento es un hash {battery: B, exams: [e1,e2,...]} %>
    <%= hash[:battery].name %>
    <ol>
      <% hash[:exams].each do |exam| %>
        <% # TODO: encontrar los form values que pertenecen a cada examen %>
        <li>
          <h3><%= exam.name %></h3>
          <ul>

            <% exam_form_values = report.form_values.where(form_field: exam.form_fields) %>
            <%= form.fields_for :form_values, exam_form_values do |f| %>
              <li>
                <div class="field">
                  <%= render "reports/fields/#{f.object.form_field.type.underscore.downcase}", f: f, exam_form_values: exam_form_values %>
                </div>
              </li>
            <% end %>

          </ul>
        </li>
      <% end %>
    </ol>
  <% end %>


  <h2>Conclusiones</h2>
  <div class="field">
    <%= form.label :conclusions %>
    <%= form.text_area :conclusions %>
  </div>

  <h2>Completar informe</h2>
  <div class="field">
    <%= form.check_box :completed, disabled: true %>
    <%= form.label :completed, 'Completado?', style: 'display:inline;' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<p>
  <strong>Completed:</strong>
  <%= @report.completed %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @report.patient %>
</p>

<p>
  <strong>Conclusions:</strong>
  <%= @report.conclusions %>
</p>

<p>
  <strong>Generado el:</strong>
  <%= display_time_from_string @snapshot['created_at'] %>
</p>

<h2>Resultados</h2>
<% @snapshot['batteries'].each do |battery| %>
  <h3><%= battery['name'] %></h3>
  <ol>
    <% battery['exams'].each do |exam| %>
      <li>
        <h4><%= exam['name'] %></h4>
        <ul>
          <% exam['fields'].each do |field| %>
            <li>
              <%= field['label'] %>: <%= field['value'] %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ol>
<% end %>

app/views/reports/_result_fields.html.erb
<fieldset>
  <%= f.hidden_field :report_id, value: @report.id %>
  <%= f.hidden_field :indicator_id, value: f.object.indicator.id %>

  <%= f.object.indicator.name %> (<%= f.object.indicator.unit %>):

  <div class="fields">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>
</fieldset>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= form_with(model: @report, url: complete_report_path, method: :get, local: true) do |f| %>
  <%= f.submit 'Completar' %>
<% end %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Completed</th>
      <th>Patient</th>
      <th>Conclusions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.completed %></td>
        <td><%= report.patient %></td>
        <td><%= report.conclusions %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<% if @snapshot.nil? %>
  <h1>No existe reporte para mostrar.</h1>
<% else %>
  <%= render 'report' %>
<% end %>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>